-- =====================================================
-- CUSTOMER ANALYTICS & BEHAVIOR TRACKING SYSTEM
-- =====================================================

-- 1. Customer events tracking table
CREATE TABLE IF NOT EXISTS public.customer_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID REFERENCES public.customers(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL, -- page_view, product_view, add_to_cart, remove_from_cart, checkout_start, purchase, cart_abandon, etc
  event_data JSONB, -- Flexible data for each event
  session_id TEXT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_customer_events_customer_id ON public.customer_events(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_events_user_id ON public.customer_events(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_events_type ON public.customer_events(event_type);
CREATE INDEX IF NOT EXISTS idx_customer_events_created_at ON public.customer_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customer_events_session ON public.customer_events(session_id);

-- Enable RLS
ALTER TABLE public.customer_events ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Admins can view all events"
  ON public.customer_events
  FOR SELECT
  TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can insert own events"
  ON public.customer_events
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Anonymous users can insert events"
  ON public.customer_events
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- 2. Customer insights table (generated by AI analysis)
CREATE TABLE IF NOT EXISTS public.customer_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  insight_type TEXT NOT NULL, -- abandoned_cart, browse_no_purchase, high_value_potential, product_recommendations, etc
  insight_data JSONB NOT NULL,
  priority TEXT DEFAULT 'medium', -- low, medium, high, urgent
  status TEXT DEFAULT 'new', -- new, contacted, converted, ignored
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  UNIQUE(customer_id, insight_type, created_at)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_customer_insights_customer_id ON public.customer_insights(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_insights_type ON public.customer_insights(insight_type);
CREATE INDEX IF NOT EXISTS idx_customer_insights_priority ON public.customer_insights(priority);
CREATE INDEX IF NOT EXISTS idx_customer_insights_status ON public.customer_insights(status);
CREATE INDEX IF NOT EXISTS idx_customer_insights_created_at ON public.customer_insights(created_at DESC);

-- Enable RLS
ALTER TABLE public.customer_insights ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Admins can manage insights"
  ON public.customer_insights
  FOR ALL
  TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role));

-- Trigger for updated_at
CREATE TRIGGER update_customer_insights_updated_at
  BEFORE UPDATE ON public.customer_insights
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- 3. Function to identify abandoned carts (run daily via cron)
CREATE OR REPLACE FUNCTION public.identify_abandoned_carts()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  abandoned_record RECORD;
BEGIN
  -- Find users who added items to cart in last 24-72 hours but didn't purchase
  FOR abandoned_record IN
    SELECT DISTINCT 
      ce.customer_id,
      ce.user_id,
      ce.event_data->'products' as cart_items,
      ce.created_at as cart_time
    FROM customer_events ce
    WHERE ce.event_type = 'add_to_cart'
      AND ce.created_at > NOW() - INTERVAL '72 hours'
      AND ce.created_at < NOW() - INTERVAL '24 hours'
      AND ce.customer_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM customer_events ce2
        WHERE ce2.customer_id = ce.customer_id
          AND ce2.event_type = 'purchase'
          AND ce2.created_at > ce.created_at
      )
      AND NOT EXISTS (
        SELECT 1 FROM customer_insights ci
        WHERE ci.customer_id = ce.customer_id
          AND ci.insight_type = 'abandoned_cart'
          AND ci.created_at > NOW() - INTERVAL '7 days'
      )
  LOOP
    -- Create insight for abandoned cart
    INSERT INTO customer_insights (
      customer_id,
      insight_type,
      insight_data,
      priority,
      expires_at
    ) VALUES (
      abandoned_record.customer_id,
      'abandoned_cart',
      jsonb_build_object(
        'cart_items', abandoned_record.cart_items,
        'cart_time', abandoned_record.cart_time,
        'message', 'Cliente adicionou produtos ao carrinho mas não finalizou a compra'
      ),
      'high',
      NOW() + INTERVAL '7 days'
    )
    ON CONFLICT (customer_id, insight_type, created_at) DO NOTHING;
  END LOOP;
END;
$$;

-- 4. Function to identify browse-no-purchase (run daily via cron)
CREATE OR REPLACE FUNCTION public.identify_browse_no_purchase()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  browse_record RECORD;
BEGIN
  -- Find users who viewed products but never added to cart
  FOR browse_record IN
    SELECT DISTINCT 
      ce.customer_id,
      ce.user_id,
      COUNT(DISTINCT ce.event_data->>'product_id') as viewed_products,
      array_agg(DISTINCT ce.event_data->>'product_id') as product_ids
    FROM customer_events ce
    WHERE ce.event_type = 'product_view'
      AND ce.created_at > NOW() - INTERVAL '7 days'
      AND ce.customer_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM customer_events ce2
        WHERE ce2.customer_id = ce.customer_id
          AND ce2.event_type IN ('add_to_cart', 'purchase')
          AND ce2.created_at > ce.created_at - INTERVAL '7 days'
      )
      AND NOT EXISTS (
        SELECT 1 FROM customer_insights ci
        WHERE ci.customer_id = ce.customer_id
          AND ci.insight_type = 'browse_no_purchase'
          AND ci.created_at > NOW() - INTERVAL '7 days'
      )
    GROUP BY ce.customer_id, ce.user_id
    HAVING COUNT(DISTINCT ce.event_data->>'product_id') >= 3
  LOOP
    -- Create insight for browse without purchase
    INSERT INTO customer_insights (
      customer_id,
      insight_type,
      insight_data,
      priority,
      expires_at
    ) VALUES (
      browse_record.customer_id,
      'browse_no_purchase',
      jsonb_build_object(
        'viewed_products_count', browse_record.viewed_products,
        'product_ids', browse_record.product_ids,
        'message', 'Cliente navegou por diversos produtos mas não adicionou nenhum ao carrinho'
      ),
      'medium',
      NOW() + INTERVAL '7 days'
    )
    ON CONFLICT (customer_id, insight_type, created_at) DO NOTHING;
  END LOOP;
END;
$$;

-- Comments
COMMENT ON TABLE public.customer_events IS 'Tracks all customer interactions and behaviors for analytics';
COMMENT ON TABLE public.customer_insights IS 'AI-generated insights about customer behavior requiring action';
COMMENT ON FUNCTION public.identify_abandoned_carts() IS 'Identifies customers with abandoned carts';
COMMENT ON FUNCTION public.identify_browse_no_purchase() IS 'Identifies customers who browse but dont purchase';